<?xml version="1.0" encoding="utf-8"?><Database Class="TrelloDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="" Member="User">
    <Type Name="User">
      <Column Member="UserID" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Member="Username" Type="System.String" CanBeNull="false" />
      <Column Member="Email" Type="System.String" CanBeNull="false" />
      <Column Member="Password" Type="System.String" CanBeNull="false" />
      <Column Member="Avatar" Type="System.String" CanBeNull="false" />
      <Association Name="BoardMember_User" Member="BoardMember" ThisKey="UserID" OtherKey="UserID" Type="BoardMember" IsForeignKey="true" />
      <Association Name="Board_User" Member="Board" ThisKey="UserID" OtherKey="AdminID" Type="Board" IsForeignKey="true" />
      <Association Name="Task_User" Member="Task" ThisKey="UserID" OtherKey="AssignedUserID" Type="Task" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="Board">
    <Type Name="Board">
      <Column Member="BoardID" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Member="Title" Type="System.String" CanBeNull="false" />
      <Column Member="AdminID" Type="System.Int32" CanBeNull="false" />
      <Association Name="Board_User" Member="User" ThisKey="AdminID" OtherKey="UserID" Type="User" />
      <Association Name="Column_Board" Member="Column" ThisKey="BoardID" OtherKey="BoardID" Type="Column" IsForeignKey="true" />
      <Association Name="BoardMember_Board" Member="BoardMember" ThisKey="BoardID" OtherKey="BoardID" Type="BoardMember" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="Column">
    <Type Name="Column">
      <Column Member="ColumnID" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Member="BoardID" Type="System.Int32" CanBeNull="false" />
      <Column Member="Title" Type="System.String" CanBeNull="false" />
      <Column Member="OrderIndex" Type="System.String" CanBeNull="false" />
      <Association Name="Column_Board" Member="Board" ThisKey="BoardID" OtherKey="BoardID" Type="Board" />
      <Association Name="Task_Column" Member="Task" ThisKey="ColumnID" OtherKey="ColumnID" Type="Task" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="BoardMember">
    <Type Name="BoardMember">
      <Column Member="BoardID" Type="System.Int32" CanBeNull="false" />
      <Column Member="UserID" Type="System.Int32" CanBeNull="false" />
      <Column Member="IsAdmin" Type="System.Boolean" CanBeNull="false" />
      <Association Name="BoardMember_User" Member="User" ThisKey="UserID" OtherKey="UserID" Type="User" />
      <Association Name="BoardMember_Board" Member="Board" ThisKey="BoardID" OtherKey="BoardID" Type="Board" />
    </Type>
  </Table>
  <Table Name="" Member="Task">
    <Type Name="Task">
      <Column Member="TaskID" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Member="ColumnID" Type="System.Int32" CanBeNull="false" />
      <Column Member="Title" Type="System.String" CanBeNull="false" />
      <Column Member="Description" Type="System.String" CanBeNull="false" />
      <Column Member="AssignedUserID" Type="System.Int32" CanBeNull="false" />
      <Association Name="Task_Column" Member="Column" ThisKey="ColumnID" OtherKey="ColumnID" Type="Column" />
      <Association Name="Task_User" Member="User" ThisKey="AssignedUserID" OtherKey="UserID" Type="User" />
      <Association Name="Checklist_Task" Member="Checklist" ThisKey="TaskID" OtherKey="TaskID" Type="Checklist" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="" Member="Checklist">
    <Type Name="Checklist">
      <Column Member="ChecklistID" Type="System.Int32" IsPrimaryKey="true" CanBeNull="false" />
      <Column Member="TaskID" Type="System.Int32" CanBeNull="false" />
      <Column Member="TaskDescription" Type="System.String" CanBeNull="false" />
      <Column Member="IsCompleted" Type="System.Boolean" CanBeNull="false" />
      <Association Name="Checklist_Task" Member="Task" ThisKey="TaskID" OtherKey="TaskID" Type="Task" />
    </Type>
  </Table>
</Database>